#!/usr/bin/env python3
import json
import sys
from pathlib import Path

def fail(msg: str) -> None:
    print(f"ERROR: {msg}")
    sys.exit(1)

def warn(msg: str) -> None:
    print(f"WARNING: {msg}")

def ok(msg: str) -> None:
    print(f"OK: {msg}")

def load_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail(f"File not found: {path}")
    except json.JSONDecodeError as e:
        fail(f"Invalid JSON: {path} ({e})")

def is_obj(x): return isinstance(x, dict)
def is_list(x): return isinstance(x, list)
def has(x, k): return is_obj(x) and k in x

def validate_ai_trust_hub(doc: dict):
    # TFWS v2 onetoo.eu shape (permissive):
    # must contain at least one of these: signals/endpoints/resources
    if not any(k in doc for k in ("signals", "endpoints", "resources", "hub", "links")):
        warn("ai-trust-hub: expected one of fields: signals/endpoints/resources/hub/links (permissive)")
    # optional metadata
    for k in ("contact", "contacts", "about", "notes", "repo", "public_key", "generated_by", "timestamp"):
        if k in doc and not isinstance(doc[k], (str, list, dict, int, float, bool, type(None))):
            fail(f"ai-trust-hub: field '{k}' has unexpected type")

def validate_key_history(doc: dict):
    # TFWS v2 onetoo.eu shape (permissive):
    # allow either "keys" (list) or "history" (list)
    if "keys" in doc:
        if not is_list(doc["keys"]):
            fail("key-history: 'keys' must be a list")
    elif "history" in doc:
        if not is_list(doc["history"]):
            fail("key-history: 'history' must be a list")
    else:
        warn("key-history: expected 'keys' or 'history' list (permissive)")

def validate_tfws_adoption(doc: dict):
    # Adoption manifest v1 (as generated by our generator)
    if "adoption" not in doc or not is_obj(doc.get("adoption")):
        fail("tfws-adoption: missing object field 'adoption'")
    a = doc["adoption"]
    if "self_declared" not in a or not isinstance(a["self_declared"], bool):
        fail("tfws-adoption: adoption.self_declared must be boolean")
    if "no_central_authority" not in a or not isinstance(a["no_central_authority"], bool):
        fail("tfws-adoption: adoption.no_central_authority must be boolean")

def detect_kind(doc: dict, filename: str) -> str:
    name = filename.lower()
    if "key-history" in name or ("keys" in doc) or ("history" in doc):
        return "key-history"
    if "adoption" in name or "adoption" in doc:
        return "tfws-adoption"
    if "trust" in name or "hub" in name or any(k in doc for k in ("signals", "endpoints", "resources", "hub", "links")):
        return "ai-trust-hub"
    return "unknown"

def main():
    if len(sys.argv) < 2:
        print("Usage: tfws-validate.py <file.json>")
        sys.exit(2)

    path = Path(sys.argv[1]).resolve()
    doc = load_json(path)

    if not is_obj(doc):
        fail("Top-level JSON must be an object")

    kind = detect_kind(doc, path.name)

    if kind == "ai-trust-hub":
        validate_ai_trust_hub(doc)
        ok(f"Valid (permissive) ai-trust-hub: {path}")
    elif kind == "key-history":
        validate_key_history(doc)
        ok(f"Valid (permissive) key-history: {path}")
    elif kind == "tfws-adoption":
        validate_tfws_adoption(doc)
        ok(f"Valid tfws-adoption: {path}")
    else:
        warn("Unknown doc type; no specific checks applied")
        ok(f"Basic validation passed: {path}")

if __name__ == "__main__":
    main()
